---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pool.dataverse.redhat.com
  resources:
  - resourcebids
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pool.dataverse.redhat.com
  resources:
  - resourcebids/finalizers
  verbs:
  - update
- apiGroups:
  - pool.dataverse.redhat.com
  resources:
  - resourcebids/status
  verbs:
  - get
  - patch
  - update
