apiVersion: pool.dataverse.redhat.com/v1alpha1
kind: ResourceClaim
metadata:
  name: test-claim-2
  namespace: default
spec:
  type: snowflake
  leaseDuration: 1m
  requiredLabels:
    environment: test
